[package]
name = "client"
version = "0.1.0"
authors = ["Ana Gelez <ana@gelez.xyz>"]
edition = "2018"

[dependencies]
bevy = { version = "0.4", default-features = false, features = [
    "bevy_gltf",
    "bevy_winit",
    "bevy_wgpu",
    "render",
    "png",
    "wayland",
    "x11",
] }
